import type { PlaceDetail } from "../domain/place-detail";

export const placeDetailTestData: PlaceDetail = {
  address: "12 Đường Test",
  areas: [
    {
      description: "Không gian có máy lạnh",
      id: "test-area-1",
      isSimulated: true,
      name: "Khu trong nhà",
    },
  ],
  currency: "VND",
  description: null,
  district: "Quận 3",
  estimatedCapacity: 40,
  id: "test-place-id",
  isSimulated: true,
  latitude: 10.78,
  longitude: 106.687,
  media: [
    {
      altText: "Góc cửa sổ thử nghiệm",
      height: 800,
      id: "test-media-1",
      isSimulated: true,
      sortOrder: 0,
      sourceLabel: "Minh họa giả lập của Chốn",
      sourceReference: "test-seed-v1",
      url: "/place-media/synthetic/cafe-window.svg",
      width: 1200,
    },
    {
      altText: "Góc đọc sách thử nghiệm",
      height: 800,
      id: "test-media-2",
      isSimulated: true,
      sortOrder: 1,
      sourceLabel: "Minh họa giả lập của Chốn",
      sourceReference: "test-seed-v1",
      url: "/place-media/synthetic/cafe-reading.svg",
      width: 1200,
    },
  ],
  name: "Góc Test",
  openingHours: {
    timezone: "Asia/Ho_Chi_Minh",
    weekly: {
      friday: [{ closes: "22:00", opens: "07:00" }],
      monday: [{ closes: "22:00", opens: "07:00" }],
      saturday: [{ closes: "23:00", opens: "08:00" }],
      sunday: [],
      thursday: [{ closes: "22:00", opens: "07:00" }],
      tuesday: [{ closes: "22:00", opens: "07:00" }],
      wednesday: [{ closes: "22:00", opens: "07:00" }],
    },
  },
  priceLevel: 2,
  sizeCategory: "medium",
  slug: "goc-test",
  typicalSpendMax: 90_000,
  typicalSpendMin: 45_000,
};
